name: flutter_ozow
description: A simple flutter plugin to integrate Ozow payment gateway into your flutter app.
version: 1.1.0
homepage: "https://under-flow.web.app"
repository: "https://github.com/Miso-0/flutter_ozow.git"

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.3
  dio: ^5.3.3
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - packages/flutter_ozow/assets/


